# Generated by Django 5.0.4 on 2024-04-28 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('institute', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('ONLINE', 'online'), ('OFFLINE', 'offline')], default='OFFLINE', max_length=7)),
                ('venue', models.CharField(max_length=500)),
                ('chairPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairPerson', to='api.user')),
                ('keynoteSpeaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keynoteSpeaker', to='api.user')),
                ('proramCoordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proramCoordinator', to='api.user')),
            ],
        ),
    ]
