# Generated by Django 5.0.4 on 2024-04-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='institute',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
