# Generated by Django 4.2.11 on 2024-04-28 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_opportunities_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsevents',
            name='proramCoordinator',
        ),
        migrations.AddField(
            model_name='newsevents',
            name='programCoordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programCoordinator', to='api.user'),
            preserve_default=False,
        ),
    ]
