# Generated by Django 4.2.11 on 2024-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_newsevents_proramcoordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='is_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
