# Generated by Django 5.0.4 on 2024-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gallery_is_home_page_newsevents_is_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsevents',
            name='chairPerson',
        ),
        migrations.RemoveField(
            model_name='newsevents',
            name='keynoteSpeaker',
        ),
        migrations.RemoveField(
            model_name='newsevents',
            name='programCoordinator',
        ),
        migrations.AddField(
            model_name='newsevents',
            name='chairPerson',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='chairPerson', to='api.user'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='keynoteSpeaker',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='keynoteSpeaker', to='api.user'),
        ),
        migrations.AddField(
            model_name='newsevents',
            name='programCoordinator',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='programCoordinator_events', to='api.user'),
        ),
    ]
