# Generated by Django 5.0.4 on 2024-04-30 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_newsevents_chairperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsevents',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='chairPerson',
            field=models.ManyToManyField(blank=True, default=None, related_name='chairPerson', to='api.user'),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='keynoteSpeaker',
            field=models.ManyToManyField(blank=True, default=None, related_name='keynoteSpeaker', to='api.user'),
        ),
        migrations.AlterField(
            model_name='newsevents',
            name='programCoordinator',
            field=models.ManyToManyField(blank=True, default=None, related_name='programCoordinator_events', to='api.user'),
        ),
    ]
